### ISSUE TITLE
Добавить все ксс переменные

### ISSUE THREAD

**Issue by dacorm** [we-ourselves-and-ai/aiq#2]
Добавить ксс переменные в файлы app/styles/dark (light)

из экрана https://www.figma.com/file/7QqJFJI8l7PtG1n9WCdhgT/Neuro-Social-Media?type=design&node-id=18-2744&mode=design&t=qKHhNviOexBuRNXP-4

название должно быть в формате
--название из фигмы

**Comment by alinamr** [comment]
взяла в работу

**Comment by dacorm** [comment]
Закрыто, сделано
