### ISSUE TITLE
Вынести компонент MainPage

### ISSUE THREAD

**Issue by dacorm** [we-ourselves-and-ai/aiq#4]
В файле Routes есть вот это

` <div>
        main route
        <button onClick={() => openPage($router, 'profile', null)}></button>
        <ThemeChanger />
      </div>`

Вместо этого должно быть просто <MainPage />

Вынести МейнПейдж в директорию pages, структура должна быть такой же как у компонента Profile в директории Pages

**Comment by focuzzzed** [comment]
Беру на себя
